### ISSUE TITLE
script_time_network_status.lua DEVICES

### ISSUE THREAD

**Issue by jec44** [vzwingma/domotique#4]
Bonjour Vincent,

J'ai découvert votre script utilisant la Freebox pour la détection de présence et vraiment c'est excellent ! J'aimerais juste l'améliorer mais je ne sais pas comment m'y prendre, voici ma suggestion : j'aimerais en plus de l'adresse MAC récupérer le "primary_name" et ainsi en fonction de son statut "true" or "false" allumer ou non le device dans domoticz. Par exemple la XBOX : impossible à pinguer par un script, j'aimerais que le device XBOX de domoticz passe à ON lorsque le script détecte sa présence. Il faut bien sur que le device domoticz et le nom déclaré dans la Freebox soit les mêmes. 
Merci de votre aide

**Comment by vzwingma** [comment]
Bonjour,
Content que mes scripts servent à quelqu'un d'autre !

Pour trouver le primary name, il faut modifier le script comme suit : 

- La ligne 100 du script permet de lire la réponse JSON envoyée par la Freebox. Il s'agit de la liste des périphériques associés à la freebox, sous la forme suivante (ex d'un smartphone)  : 



        {
		"l2ident": {
			"id": "XX:98:D1:21:49:D0",
			"type": "mac_address"
		},
		"active": false,
		"id": "ether-XX:98:d1:21:49:d0",
		"last_time_reachable": 1445975888,
		"persistent": true,
		"names": [{
			"name": "Windows-Phone",
			"source": "dhcp"
		}],
		"vendor_name": "",
		"host_type": "smartphone",
		"l3connectivities": [{
			"addr": "999.168.0.31",
			"active": false,
			"reachable": false,
			"last_activity": 1445975888,
			"af": "ipv4",
			"last_time_reachable": 1445975888
		},
		{
			"addr": "xx80::34a1:9812:9b02:ba7",
			"active": false,
			"reachable": false,
			"last_activity": 1444715744,
			"af": "ipv6",
			"last_time_reachable": 1444715744
		},
		{
			"addr": "xx80::bd49:56a0:9eee:a983",
			"active": false,
			"reachable": false,
			"last_activity": 1445975834,
			"af": "ipv6",
			"last_time_reachable": 1445975834
		}],
		"reachable": false,
		"last_activity": 1445975888,
		"primary_name_manual": false,
		"primary_name": "Windows-Phone"
	    },


- A partir de la ligne 103, on parcourt la liste des périphériques avec la variable `peripherique` qui représente une réponse comme ci dessous.
Il est possible de naviguer dans l'arbre de la réponse JSON, par exemple pour récupérer l'id `		"id": "ether-XX:98:d1:21:49:d0",`il suffit d'appeler `peripherique.id`.

Dans votre cas, pour récupérer le primary_name, il suffit d'appeler `peripherique.primary_name`
(Il y a un exemple dans le [log](https://github.com/vzwingma/domotique/blob/master/domoticz/scripts/lua/script_time_network_status.lua#L109) du périphérique ( commit 246a7704340ba810215e5ecf4423c910d4936e44)

Ainsi pour trouver l'état de la XBox, vous pouvez supprimer les boucles de split de la liste des adresses [MAC](https://github.com/vzwingma/domotique/blob/master/domoticz/scripts/lua/script_time_network_status.lua#L105-L106), et modifier la ligne [107](https://github.com/vzwingma/domotique/blob/master/domoticz/scripts/lua/script_time_network_status.lua#L107) de la sorte : 

      if("nom de la XBOX" == peripherique.primary_name and peripherique.active and peripherique.reachable) then
         Mettre à jour le device XBOX dans Domoticz


-  Pour la mise à du device dans Domoticz, il suffit d'ajouter la ligne suivante : 

     commandArray['Nom du device XBOX dans domoticz']="On" ou "Off"


Ce qui peut donner : 

       if("nom de la XBOX" == peripherique.primary_name and peripherique.active and peripherique.reachable) then
              commandArray['Nom du device XBOX dans domoticz']="On"
       else
              commandArray['Nom du device XBOX dans domoticz']="Off"
       end

- Remarques complémentaires : 
     - Le nom du primary name de la XBox sur la freebox et le nom du device Xbox dans Domoticz peuvent ne pas être les mêmes.
     - Une bonne pratique est de ne pas les écrire en dur dans le code. Si pour une raison ou une autre, les valeurs changent il faudrait modifier le script. Le plus simple est de déclarer 2 User Variables dans Domoticz pour stocker ces deux noms. Ensuite, elles sont accessibles dans le script Lua avec `uservariables["nom de la variable dans Domoticz"]`


J'espère que cela vous aide et n'hésitez pas à faire vos remarques ou vos questions.

Vincent

**Comment by vzwingma** [comment]
Sans réponse, je considère que l'issue #4 est close
