### ISSUE TITLE
erreur script_time_network_status.lua 

### ISSUE THREAD

**Issue by mpetit** [vzwingma/domotique#5]
Bonjour,

Quand j'essaye de lancer la commande **lua script_time_network_status.lua**, j'obtiens systématiquement un message d'erreur : 
_attempt to index global 'uservariables' (a nil value)_
pourtant j'ai bien crée une variable user : _freebox_mac_adress_smartphones_ 
pouvez-vous me dire ou se trouve le problème ?

Merci encore

**Comment by vzwingma** [comment]
Bonjour,

Le script est conçu pour être utilisé dans le cadre du système DomoticZ; car c'est DomoticZ qui se charge d'initialiser le tableau 'uservariables' et de déclencher le script. Il n'est pas destiné à être déclenché manuellement avec la commande lua. 
(Je ne sais pas quelles sont les commandes réalisées par DomoticZ pour initialiser les variables et déclencher le script)

Utilisez vous le script dans le cadre du répertoire /scripts de DomoticZ ?

Si vous souhaitez déclencher le script manuellement, vous pouvez définir les valeurs directement dans le script, plutôt qu'utiliser 'uservariables' : 
Par exemple, écrire directement  : 
freebox_mac_adress_smartphones="192.168.x.x"

**Comment by mpetit** [comment]
Bonsoir,

Merci pour votre retour, 
- le script est dans le répertoire /home/pi/domoticz/script/lua, 
- uservariable est bien positionnée : 
    variable : freebox_mac_adress_smartphones
    type de variable : String
    Current value : 4C:7C:5F:D0:xxxxx 
   
étant donné que c'est un script_time, et d'après ce que j'ai compris, Domoticz va exécuter le script toutes les minutes.
dans les logs, je reçois le message suivant : 
**_2016-07-26 20:59:00.451 Error: EventSystem: in /home/pi/domoticz/scripts/lua/script_time_network_status.lua: ...e/pi/domoticz/scripts/lua/script_time_network_status.lua:5: attempt to index global 'freebox_apptoken' (a nil value)_**

Cordialement

**Comment by vzwingma** [comment]
Bonjour,

Oui, c'est bien le fonctionnement des scripts de type "time", le script se déclenche toutes les minutes.
Selon le message d'erreur, il lui manque la variable **freebox_apptoken** déclarée dans Domoticz
(et enfin, il faut vérifier que la variable **freebox_appid** est également déclarée.

Pour obtenir ces informations,  il est nécessaire de les demander à la freebox. La procédure est décrite ici : http://dev.freebox.fr/sdk/os/login/. Il faut faire une requête POST à l'URL suivante : http://mafreebox.freebox.fr/api/v3/login/authorize/

avec les informations suivantes dans le body HTTP : 
{
   "app_id": "xxxxxx",   ==> Cette valeur doit être la même que la variable freebox_appid dans DomoticZ
   "app_name": "xxxxx",
   "app_version": "1.0",
   "device_name": "****"
}

**Comment by mpetit** [comment]
Bonsoir,

après avoir fait plusieurs tests, cela marche voila comment j'ai procédé

- freebox_apptoken directement dans le script

- il semblerait qu'il y ait un bug ou un changement de gestion des autorisations des applications sur la freebox: la réponse a été trouvée à cette adresse : http://dev.freebox.fr/bugs/task/13811

Voila, merci tout de même pour ton script il est juste excellent

**Comment by vzwingma** [comment]
Merci pour l'information sur le bug sur la freebox. Je l'ajoute à ma documentation pour le prochain qui demandera.
